### ISSUE TITLE
Missing tags & commits on Git, no PyPy sdist

### ISSUE THREAD

**Issue by mweinelt** [OHF-Voice/intents-package#3]
Hi!

PyPi has the latest releases, and they are missing as Tags on this repository. Can you put them up?

I'm mostly interested in 2024.2.2 right now, but 2024.2.1 and 2024.1.29 are also missing.

Thanks!

**Comment by mweinelt** [comment]
PyPi is misisng the sdist for the 2024.4.3 release, so I thought I could turn back to the Git repository, but it is missing both the commits as well as the latest tags.

Please push them. Thank you!

**Comment by mweinelt** [comment]
Hey, @synesthesiam! Not sure if you're watching issues here, given that the issue is two months old already, so I thought I'd ping you. Hope that's fine.

**Comment by dotlambda** [comment]
Maybe @andrejs2 can help?

**Comment by synesthesiam** [comment]
Sorry for the delay! I pushed the commits up and added the tag. I will add sdists to PyPI here shortly.

**Comment by mweinelt** [comment]
Thanks!

**Comment by mweinelt** [comment]
Home-Assistant 2024.5.0 requires version 2024.4.24 for which no tag exists.

@synesthesiam PTAL :)

**Comment by dotlambda** [comment]
@andrejs2?

**Comment by andrejs2** [comment]
> @andrejs2?

Sorry, I think it's a mistake...I'm only (only) a language leader for Slovenian...I'm not a dev.

**Comment by dotlambda** [comment]
Sorry for the pings then!

**Comment by synesthesiam** [comment]
Add tags

**Comment by mweinelt** [comment]
@synesthesiam The 2024.7.29 bump is missing :wink:

**Comment by synesthesiam** [comment]
Fixed :+1:

**Comment by mweinelt** [comment]
Hey, we're missing the 2025.7.30 tag now.

 https://pypi.org/project/home-assistant-intents/

And I will suggest moving to [trusted publishing](https://docs.pypi.org/trusted-publishers/) as suggested in https://developers.home-assistant.io/docs/core/integration-quality-scale/rules/dependency-transparency/, if that is possible, to prevent this issue from reappearing.

**Comment by mweinelt** [comment]
The 2025.9.3 tag is missing 🥲
